language: c
before_script:
# We want to try perl standalone first
  - sudo apt-get update
  - sudo apt-get install cpanminus nsis valgrind gdb
  - sudo cpanm --notest Archive::Tar Config::AutoConf::INI ExtUtils::CBuilder File::chdir File::Basename File::Find File::Path File::Copy::Recursive File::Temp IPC::Run Perl::OSType
  - sh ./install-c-genericLogger.sh
script:
# Enable unlimited core file size
  - ulimit -c unlimited -S
# We want to try perl standalone first
  - perl CMakeObjects.PL
  - rm -rf output
# ALL_IN_ONE
  - cmake -DICU_DEBUG=TRUE -DALL_IN_ONE=ON .
  - make check
  - make pack
  - cpack -G NSIS
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
# Not ALL_IN_ONE
  - cmake -DICU_DEBUG=TRUE .
  - make check
  - make pack
  - cpack -G NSIS
  - sudo make install
  - tconv -b 3 -C ICONV -f ASCII -t UTF-16LE -o /tmp/tconv.tconv-ICONV-UTF-16LE.c src/tconv.c
  - tconv -b 3 -C ICU   -f ASCII -t UTF-16LE -o /tmp/tconv.tconv-ICU-UTF-16LE.c src/tconv.c
  - iconv -f ASCII -t UTF-16LE -o /tmp/tconv.iconv-UTF-16LE.c src/tconv.c
  - uconv -f ASCII -t UTF-16LE -o /tmp/tconv.uconv-UTF-16LE.c src/tconv.c
  - ls -l src/tconv.c /tmp/tconv.iconv-UTF-16LE.c /tmp/tconv.uconv-UTF-16LE.c /tmp/tconv.tconv-ICONV-UTF-16LE.c /tmp/tconv.tconv-ICU-UTF-16LE.c
  - file src/tconv.c /tmp/tconv.iconv-UTF-16LE.c /tmp/tconv.uconv-UTF-16LE.c /tmp/tconv.tconv-ICONV-UTF-16LE.c /tmp/tconv.tconv-ICU-UTF-16LE.c
  - diff /tmp/tconv.iconv-UTF-16LE.c /tmp/tconv.tconv-ICONV-UTF-16LE.c
  - diff /tmp/tconv.iconv-UTF-16LE.c /tmp/tconv.tconv-ICU-UTF-16LE.c
  - diff /tmp/tconv.uconv-UTF-16LE.c /tmp/tconv.tconv-ICONV-UTF-16LE.c
  - tconv -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - rm -rf output CMakeCache.txt CMakeFiles
# Not ALL_IN_ONE and codecov
  - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DICU_DEBUG=TRUE .
  - make
  - make check
  - ./output/lib/tconv --help
  - ./output/lib/tconv --usage
  - ./output/lib/tconv -V
  - ./output/lib/tconv --bufsize 3 --convert-engine XXXXX --from-code ASCII --to-code UTF-16 --output /tmp/tconv.tconv-ICONV-UTF-16.c -- src/tconv.c
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c -G XXXXX
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c -G ICU
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c -G CCHARDET
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        XXXXXX -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c || [ $? -ne 0 ]
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /etc/passwd                     src/tconv.c || [ $? -ne 0 ]
  - ./output/lib/tconv -b        3 -C               ICONV -f          ASCII -t        UTF-16 -o       /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c
  - ./output/lib/tconv --bufsize 3 --convert-engine ICONV --from-code ASCII --to-code UTF-16 --output /tmp/tconv.tconv-ICONV-UTF-16.c src/tconv.c
  - ./output/lib/tconv -b 3 -C ICU   -f ASCII -t UTF-16 -o /tmp/tconv.tconv-ICU-UTF-16.c src/tconv.c
  # Same charset is nothing special in ICU builtin
  - ./output/lib/tconv -C ICU -f UTF-16 -t UTF-16 -o /dev/null /tmp/tconv.tconv-ICU-UTF-16.c
  # Same charset is a special thing in ICONV builtin
  - ./output/lib/tconv -C ICONV -f UTF-16 -t UTF-16 -o /dev/null /tmp/tconv.tconv-ICONV-UTF-16.c
  # TRANSLIT is nothing special in ICONV builtin
  - ./output/lib/tconv -C ICONV -f UTF-16 -t ASCII//TRANSLIT -o /tmp/tconv.tconv-ICONV-ASCII-TRANSLIT.c /tmp/tconv.tconv-ICU-UTF-16.c
  # TRANSLIT is a special path in ICU builtin
  - ./output/lib/tconv -C ICU -f UTF-16 -t ASCII//TRANSLIT -o /tmp/tconv.tconv-ICU-ASCII-TRANSLIT.c /tmp/tconv.tconv-ICU-UTF-16.c
  # Charset discovery
  - ./output/lib/tconv --charset-engine CCHARDET -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - ./output/lib/tconv --charset-engine ICU -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - ./output/lib/tconv --charset-engine XXXXXXXX -g `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f | tail -1`
  # Signature is specific to ICU
  - TCONV_ENV_CONVERT_ICU_SIGNATURE=-1 ./output/lib/tconv -C ICU -f UTF-16 -t UTF-8 -o /tmp/tconv.tconv-ICU-UTF8-SIGNATURE.c /tmp/tconv.tconv-ICU-UTF-16.c
  - TCONV_ENV_CONVERT_ICU_SIGNATURE=1 ./output/lib/tconv -C ICU -f UTF-16 -t UTF-8 -o /tmp/tconv.tconv-ICU-UTF8-SIGNATURE.c /tmp/tconv.tconv-ICU-UTF-16.c
  - TCONV_ENV_CONVERT_ICU_SIGNATURE=0 ./output/lib/tconv -C ICU -f UTF-16 -t UTF-8 -o /tmp/tconv.tconv-ICU-UTF8-SIGNATURE.c /tmp/tconv.tconv-ICU-UTF-16.c
  # A special case when ICU internal translit buffer need to increase
  - ./output/lib/tconv -C ICU -t UTF-8//TRANSLIT ./3rdparty/output/cchardet-1.0.0/test/testdata/wikipediaTw_One_Thousand_and_One_Nights_GB2312.txt -o /dev/null
  # Forces some internal buffers to reallocate
  - ./output/lib/tconv -C ICONV -t ASCII//TRANSLIT -b 10000 ./output/3rdparty/cchardet-1.0.0/test/testdata/wikipediaJa_One_Thousand_and_One_Nights_SJIS.txt -o /dev/null
  - ./output/lib/tconv -C ICU   -t ASCII//TRANSLIT -b 10000 ./output/3rdparty/cchardet-1.0.0/test/testdata/wikipediaJa_One_Thousand_and_One_Nights_SJIS.txt -o /dev/null
  # ICONV charset not found
  - ./output/lib/tconv -v -F -C ICONV -f MS-ANSI -t MS-ANSI -o /dev/null ./src/tconv/convert/alias.c
  # ICONV charset not found and maybe EBADF
  - ./output/lib/tconv -v -C ICONV -f MS-ANSI -t ANSI -o /dev/null ./src/tconv/convert/alias.c
  # Retry all types, printing found code
  - ./output/lib/tconv -G CCHARDET -C ICONV -F -t ASCII//TRANSLIT -o /dev/null `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - ./output/lib/tconv -G ICU      -C ICONV -F -t ASCII//TRANSLIT -o /dev/null `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - ./output/lib/tconv -G CCHARDET -C ICU   -F -t ASCII//TRANSLIT -o /dev/null `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  - ./output/lib/tconv -G ICU      -C ICU   -F -t ASCII//TRANSLIT -o /dev/null `find ./output/3rdparty/cchardet-1.0.0/test/testdata/ -type f`
  # Build coverage
  - make gcov

after_success:
- bash <(curl -s https://codecov.io/bash) -X gcov
